service: contract-testing-provider

app: contract-testing

frameworkVersion: "2"

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-offline

package:
  individually: true

useDotenv: true

custom:
  serverless-offline:
    httpPort: 4000
  stages:
    - dev
    - staging
    - prod
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
  serverless-iam-roles-per-function:
    defaultInherit: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - SNS:Publish
          Resource: "*"
  stackName: ${self:service}
  lambdaHashingVersion: 20201221
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL}
    PERSON_TOPIC_ARN: arn:aws:sns:eu-north-1:626288608949:${self:app}-${self:provider.stage}-personTopic

functions:
  personProvider:
    handler: src/functions/personProvider.handler
    name: ${self:service}-${self:provider.stage}-personProvider
    events:
      - http:
          method: post
          path: sender
