name: can-i-deploy-action

description: Check if it is safe to deploy

runs:
  using: "composite"
  steps:
    - name: Setup pact-cli
      run: docker pull pactfoundation/pact-cli:latest
      shell: bash
    - name: Can I deploy?
      run: >
        docker run pactfoundation/pact-cli:latest
        broker can-i-deploy
        --pacticipant $PACTICIPANT 
        --version ${{ github.sha }}
        --to ${{ github.base_ref }}
        --retry-while-unknown 3 
        --retry-interval 10
        --broker-base-url $PACT_BROKER_BASE_URL
        --broker-token $PACT_BROKER_TOKEN
      shell: bash
