name: contract-test

on:
  pull_request:
    types: [opened, synchronize]

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACTICIPANT: person-provider
  CI_VERSION: ${{ github.event.pull_request.head.sha }}
  GIT_BRANCH: ${{ github.head_ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Deployment Check
        run: >
          yarn pact-broker can-i-deploy 
          -a $PACTICIPANT 
          -e $CI_VERSION 
          --to ${{ github.base_ref }} 
          -b $PACT_BROKER_BASE_URL 
          -k $PACT_BROKER_TOKEN
