name: contract-test

on:
  workflow_dispatch:
    inputs:
      CONSUMER_VERSION_TAGS:
        description: Tag of consumer contract to verify against
        required: true

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  PACTICIPANT: person-provider

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
        env:
          CONSUMER_BRANCH: ${{ github.event.inputs.CONSUMER_VERSION_TAGS }}
          GIT_BRANCH: master
          CI_VERSION: ${{ github.sha }}
