name: contract-test

on:
  workflow_dispatch:
    inputs:
      CONSUMER_VERSION_TAGS:
        description: Tag of consumer contract to verify against
        required: true

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  PACTICIPANT: person-provider
  CONSUMER_BRANCH: ${{ github.event.inputs.CONSUMER_VERSION_TAGS }}
  GIT_BRANCH: master
  CI_VERSION: ${{ github.sha }}

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Deployment Check
        run: >
          yarn pact-broker can-i-deploy --pacticipant $PACTICIPANT 
            --version $CI_VERSION
            --to $CONSUMER_BRANCH
            --retry-while-unknown 0
            --retry-interval 10
            --broker-base-url $PACT_BROKER_BASE_URL
            --broker-token $PACT_BROKER_TOKEN
