name: contract-test-dev

on:
  pull_request:
    branches:
      - dev

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  PACTICIPANT: person-provider
  APP_ENVIRONMENT: dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup pact-cli
        run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: >
          docker run pactfoundation/pact-cli:latest
          broker can-i-deploy
          --pacticipant $PACTICIPANT 
          --version ${{ github.sha }}
          --to $APP_ENVIRONMENT
          --broker-base-url $PACT_BROKER_BASE_URL
          --broker-token $PACT_BROKER_TOKEN
