name: contract-test

on:
  pull_request:
    types: [opened, synchronize]

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  PACTICIPANT: person-provider
  CONSUMER_BRANCH: ${{ github.base_ref }}
  GIT_BRANCH: ${{ github.head_ref }}
  CI_VERSION: ${{ github.event.pull_request.head.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Deployment Check
        run: >
          yarn can-i-deploy
            --pacticipant $PACTICIPANT 
            --version $CI_VERSION
            --to $CONSUMER_BRANCH
            --retry-while-unknown 0
            --retry-interval 10
            --broker-base-url $PACT_BROKER_BASE_URL
            --broker-token $PACT_BROKER_TOKEN
