name: test-and-release

on: push

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
        env:
          CI_VERSION: ${{ github.sha }}
          GIT_BRANCH: ${{ github.ref }}
      - name: Can I deploy?
        run: >
          yarn pact-broker can-i-deploy 
          -a person-provider 
          -e ${{ github.sha }} 
          --to dev
          -b $PACT_BROKER_BASE_URL 
          -k $PACT_BROKER_TOKEN

  dev:
    needs: test
    name: Deploy to dev
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/release
        with:
          stage: dev

  staging:
    needs: dev
    name: Deploy to staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/release
        with:
          stage: staging

  prod:
    needs: staging
    name: Deploy to staging
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/release
        with:
          stage: production
