name: verify-contract

on:
  workflow_dispatch:
    inputs:
      PACT_URL:
        description: The "permalink" URL to the newly published pact
        required: true

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
        env:
          PACT_URL: ${{ github.event.inputs.PACT_URL }}
      - name: Can I deploy?
        run: >
          yarn pact-broker can-i-deploy 
          -a $person-provider 
          -e $${{ github.sha }} 
          --to master 
          -b $PACT_BROKER_BASE_URL 
          -k $PACT_BROKER_TOKEN
